import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Header from "../components/header";
import Logs from "../components/logs";
import TrafficLight from "../components/trafficLight";
import Video from "../components/video/video";
import { LogEntry } from "../models";
import styles from "../styles/Home.module.css";


const Home: NextPage = () => {
  const [prediction, setPrediction] = useState<number>(0);
  const [logs, setLogs] = useState<LogEntry[]>([]);

  const addNewLog = (
    source: string ,
    time: string,
    violence: number,
    id: string
  ) => {
    if (violence > 0.7) {
      let predict :string =  (Math.round((violence + Number.EPSILON) * 100) / 100).toString()

      const log: LogEntry = {
        source,
        time,
        id,
        violence: predict
      };
      setLogs((prevLogs) => [...prevLogs, log]);
    }

  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.mainContainer}>
        <Video onPrediction={setPrediction} onSetLogs={addNewLog}/>
        <TrafficLight prediction={prediction} />
        <Logs logs={logs} />
      </div>
    </div>
  );
};

export default Home;
